### ISSUE TITLE
Requests Time Out After Changing Ruby Files

### ISSUE THREAD

**Issue by d0liver** [testdouble/cypress-rails#117]
Using `bin/rake cypress:open`, I'm able to connect with Cypress and run my tests successfully once. However, if I then change `.rb` files and rerun my tests in Cypress, all subsequent requests fail until I kill and restart Cypress/Rails. This makes debugging integration issues difficult.

**Comment by searls** [comment]
This isn't good! I have definitely seen this in some cases. I'm curious, could you please post a minimal reproduction repo? If it's hard to reproduce in a minimal case I think I'll need your help in debugging the root cause (I'd start looking around class caching, autoloading, spring, etc)

**Comment by d0liver** [comment]
Hey, sorry that I didn't get back to you sooner. The issue here was that the Cypress test cases were just timing out because Rails was taking a *really long time* to respond after restarts. Thanks for your help.
