### ISSUE TITLE
cypress:run failing on CircleCI

### ISSUE THREAD

**Issue by berniechiu** [testdouble/cypress-rails#134]
Thank you all for the gem. Currently we're able to run the command successfully in local test environment.

`CYPRESS_RAILS_CYPRESS_OPTS="--browser chrome" RAILS_ENV=test rails cypress:run`

We already have a success `rspec` tests on CircleCI, however when we want to include the Cypress with the same command, seems to fail abruptly. Not sure if anyone has encountered this. Thanks!

<img width="1076" alt="Screen Shot 2022-09-29 at 7 08 37 AM" src="https://user-images.githubusercontent.com/2749593/192903996-e9b056ab-a307-42ef-8b9b-998b392863ef.png">

**Comment by searls** [comment]
I don't think this is an issue with the gem. Getting Cypress + Rails to work reliably in Circle CI is, in my experience, a constantly moving target requiring a lot of effort to stay on top of the images and services that are available to the Circle runners (node, browsers, Ruby, postgres, etc). I've lost days of my life to this as well. My solution was, sadly, to move most of my projects from Circle to Heroku CI and GitHub Actions

**Comment by berniechiu** [comment]
thanks, we found the root cause.
