### ISSUE TITLE
Rails 7 MongoDB No Rollback of transactions?

### ISSUE THREAD

**Issue by perkins2099** [testdouble/cypress-rails#154]
Trying to get this gem to work with mongodb.

The data isn't being rolled back between tests and will persist until cypress is restarted and reseeds.  Also I do not see documentation on how to configure it or if there might be any differences for mongodb?

**Comment by searls** [comment]
Hello! Unfortunately, I'm not sure whether there's any relationship between ActiveRecord transactions and whatever mongo wrapper you're using. I imagine you'd probably have to roll your own using a test-specific controller endpoint.

You might have more luck with @shakacode's https://github.com/shakacode/cypress-on-rails gem, as that one is a little more robust in its configuration/customization, I believe
