### ISSUE TITLE
Incompatible with rack 3.1

### ISSUE THREAD

**Issue by keithlayne** [testdouble/cypress-rails#162]
In 3.1, rackup moved to a separate gem, so the server breaks on this line:

https://github.com/testdouble/cypress-rails/blob/main/lib/cypress-rails/server/puma.rb#L13

`Rack::Handler` is undefined in this case, but I confirmed changing that line to `Rackup::Handler` worked. 

I don't know how or if you want to deal with this, from a quick look it appears that cypress-rails doesn't have an explicit dependency on rack. 

Sorry, I don't have time to really look into this right now, for the moment I've just locked rack to 3.0, but wanted to let you know about it.

**Comment by krzysztofjablonski** [comment]
I've created a PR https://github.com/testdouble/cypress-rails/pull/163 based on code from capybara: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/registrations/servers.rb#L31

**Comment by rosston** [comment]
This should be fixed in 0.7.1 thanks to the PR from @krzysztofjablonski!
