### ISSUE TITLE
Is it possible to integrate with Percy?

### ISSUE THREAD

**Issue by gkatsanos** [testdouble/cypress-rails#24]
I was wondering if it's possible to integrate Percy with cypress-rails? https://docs.percy.io/docs/cypress

**Comment by searls** [comment]
I suspect a similar-but-separate gem could be built like this one to run Percy tests. I wonder what @fotinakis or @timhaines might think

**Comment by bolandrm** [comment]
I was thinking similarly about how this gem could be repurposed to run Detox tests (https://github.com/wix/Detox).  It seems like a common pattern - a third party testing tool that needs some hooks into rails to manage the state.

**Comment by searls** [comment]
I think I'd recommend you both to consider taking a stab at a purpose-built fork of this gem that uses the same bag-of-tricks. If this gem were to get any more glue-codey by incorporating other tools it'd be unmaintainable, I think.
