### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by aleccool213** [testdouble/cypress-rails#36]
This isn't an issue. This is just to say that you did a wonderful job with writing this Gem. Also the README was very easy to read and had all of the information I needed to get up and running.

Thanks!

**Comment by searls** [comment]
Thanks for this note, @aleccool213! You're living proof that working on open source isn't a thankless job (in fact, I've benefited immeasurably from my own participation in open source!), but it's definitely the case that it's rare to receive appreciation that's devoid of an "but it'd be really great if you also did X" request or exhortation. Thank you for the encouragement!

**Comment by bdavidxyz** [comment]
To emphasize on this : in the 4 last years using Rails, there are only 2 major improvements that drastically changed my daily job :

 - webpack(er)
 - cypress (along with this gem).

In the old days of Java, it was nearly impossible to set up functional testing (mostly with Selenium) without heavy hacks, random waiting times, and massive headaches. With Rails, Capybara made it (almost) fantastic, at least without JavaScript. But apps tend  to include more and more JS. Setup functional testing became a nightmare (again). In theory it is feasible, but in practice you spend tons of times (more than you are aware to spend) to hack CI/CD, interns’ machine, and so on.

Now you have cypress-rails. I can run each test in complete isolation, with a predictible and resettable context,  unbugged and consistent behaviour, completely agnostic to the front-end tech, extremely easy to debug, that works on CI out-of-the-box. The only missing feature is to make functional testing understandable and sharable to non-techies.

But at least we have now functional testing that just works™

After 15 years of fighting against them, I can now work happily with them. 🎉

**Comment by searls** [comment]
haha, thank you @bdavidxyz! I just realized that unless I want to invite more positivity and gratitude, I should probably close this issue.

Really, appreciate it!
