### ISSUE TITLE
Interactive rails server output and binding.pry

### ISSUE THREAD

**Issue by wyattades** [testdouble/cypress-rails#39]
This lib has been very helpful, but one Ruby/Rails feature I am missing is the `binding.pry` tool and the ability to view the Rails console output as the tests run. This has only been an issue while developing with `rake cypress:open` (for debugging weird behaviors in our Rails app), since in headless mode I only really need to look at `log/test.log` or the error output if there is one.

From what I can tell, this isn't currently possible because you start a Puma server in a new thread to support running it in parallel with the Cypress process. But I'm curious on your thoughts here.

My first (naive) idea would be to run the Cypress process in a thread instead so the user can interact with Puma, but I'm not sure if that's possible.

**Comment by searls** [comment]
Feel free to experiment (and if it bears fruit, send a PR), but this would be a pretty big change. FWIW I have been able to debug in the past with `rake cypress:open`
