### ISSUE TITLE
Is there a way to have simplecov measuring coverage ?

### ISSUE THREAD

**Issue by bdavidxyz** [testdouble/cypress-rails#50]
I'm still working on how to integrate simplecov to the tool. If I find the way, I'll write it here.

**Comment by bdavidxyz** [comment]
Ok nothing fancy. Just install the simplecov gem. 

Then add an initializer, for example config/initializers/simplecov.rb

```
if ENV['COVERAGE_PLEASE'] == 'true'
  require 'simplecov'
  SimpleCov.start 'rails' do
    coverage_dir "coverage/ruby/functional".to_s
  end
  puts "required simplecov for functional testing"
end

```

Then

bundle exec rails cypress:run COVERAGE_PLEASE=true

**Comment by searls** [comment]
yup! I wold have suggested something similar.
