### ISSUE TITLE
Question: Can this Integrate with a package like knapsack-pro-cypress?

### ISSUE THREAD

**Issue by nickytonline** [testdouble/cypress-rails#55]
Thanks for the great project! I'll preface this with I'm a Rails/Ruby newb.

I'm curious if anyone has got this to run with parallelization using [knapsack-pro-cypress](https://github.com/KnapsackPro/knapsack-pro-cypress)? I'm guessing the answer is no, because knapsack-pro-cypress calls Cypress internally using node and cypress-rails calls node from within Ruby to build the commands plus bootstrap itself.

Based on this code from [launches_cypress.rb](https://github.com/testdouble/cypress-rails/blob/39dd3b4d79af2e52506556dbb2f1667392f90112/lib/cypress-rails/launches_cypress.rb#L31-L33), it takes Cypress CLI options in, so `--parallel` would work.

```ruby
      command = <<~EXEC
        CYPRESS_BASE_URL="http://#{server.host}:#{server.port}#{config.base_path}" "#{bin}" #{command} --project "#{config.dir}" #{config.cypress_cli_opts}
      EXEC
```

But using `--parallel` requires the Cypress dashboard from what I've understood. I'm not certain of this, the last place I used Cypress had another team handle setting up parallelization on a private cloud.

knapsack-pro-cypress accepts supported Cypress CLI options, so off hand, if we were able to pass in a different node module than `cypress`, i.e. `knapsack-pro-cypress`, I think this could work.

I see in [finds_bin.rb](https://github.com/testdouble/cypress-rails/blob/1e5cc50f4234909f1d389eac0d8e59d90e3478bf/lib/cypress-rails/finds_bin.rb#L3), `cypress` is hard-coded.

```ruby
module CypressRails
  class FindsBin
    LOCAL_PATH = "node_modules/.bin/cypress"

    def call(dir = Dir.pwd)
      local_path = Pathname.new(dir).join(LOCAL_PATH)
      if File.exist?(local_path)
        local_path
      else
        "cypress"
      end
    end
  end
end
```

If an optional node module name could be passed in as an argument (default = "cypress"), then I think this could all work together.

My question turned into solutioning lol. Anyways, thoughts?

For some more context, this is currently how I [have us set up](https://github.com/forem/forem/blob/ccb8352841385d5cfb1d6a71a2f6b30941fb482b/bin/e2e#L1-L9) to run knapsack or just cypress. 

```bash
#!/bin/bash
if [ "$KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS" = "" ]; then
  KNAPSACK_PRO_ENDPOINT=https://api-disabled-for-fork.knapsackpro.com \
    KNAPSACK_PRO_MAX_REQUEST_RETRIES=0 \
    KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS=disabled-for-fork \
    npx cypress run # run without parallelization
else
  npx knapsack-pro-cypress # parallelization is available
fi
```

and Ideally have it something like this

```bash
#!/bin/bash
if [ "$KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS" = "" ]; then
  KNAPSACK_PRO_ENDPOINT=https://api-disabled-for-fork.knapsackpro.com \
    KNAPSACK_PRO_MAX_REQUEST_RETRIES=0 \
    KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS=disabled-for-fork \
    npx cypress run # run without parallelization
else
  bundle exec rake cypress:run["knapsack-pro-cypress"] # parallelization is available
fi
```

Also, I'm happy to contribute to any work this would involve.

**Comment by searls** [comment]
One thing that would likely work in your case is to not install cypress locally to the project (such that `"node_modules/.bin/cypress"`) did not resolve, and then to put a custom script on your PATH named `cypress` that calls the thing you want.

I don't think I'd be eager to add an additional option for custom / non-cypress executables

**Comment by nickytonline** [comment]
Thanks for chiming in @searls! I'll try out your suggestion.
