### ISSUE TITLE
`cypress-rails` will not start on rails 6.1.4

### ISSUE THREAD

**Issue by grxy** [testdouble/cypress-rails#88]
Here are the logs I get when running `bin/rails cypress:open` on my computer and `bin/rails cypress:run` in CI:

```
bin/rails cypress:open

cypress-rails configuration:
============================
 CYPRESS_RAILS_DIR....................."..."
 CYPRESS_RAILS_HOST...................."..."
 CYPRESS_RAILS_PORT...................."9400"
 CYPRESS_RAILS_BASE_PATH..............."/"
 CYPRESS_RAILS_TRANSACTIONAL_SERVER....true
 CYPRESS_RAILS_CYPRESS_OPTS............""

Traceback (most recent call last):
	11: from /path/to/gems/cypress-rails-0.5.0/exe/cypress-rails:13:in `<main>'
	10: from /path/to/gems/cypress-rails-0.5.0/lib/cypress-rails/open.rb:11:in `call'
	 9: from /path/to/gems/cypress-rails-0.5.0/lib/cypress-rails/launches_cypress.rb:20:in `call'
	 8: from /path/to/gems/cypress-rails-0.5.0/lib/cypress-rails/manages_transactions.rb:10:in `begin_transaction'
	 7: from /path/to/gems/cypress-rails-0.5.0/lib/cypress-rails/manages_transactions.rb:59:in `gather_connections'
	 6: from path/to/gems/cypress-rails-0.5.0/lib/cypress-rails/manages_transactions.rb:71:in `setup_shared_connection_pool'
	 5: from /path/to/gems/cypress-rails-0.5.0/lib/cypress-rails/manages_transactions.rb:71:in `call'
	 4: from /path/to/gems/activerecord-6.1.4/lib/active_record/test_fixtures.rb:199:in `setup_shared_connection_pool'
	 3: from /path/to/gems/activerecord-6.1.4/lib/active_record/test_fixtures.rb:199:in `each'
	 2: from /path/to/gems/activerecord-6.1.4/lib/active_record/test_fixtures.rb:201:in `block in setup_shared_connection_pool'
	 1: from /path/to/gems/activerecord-6.1.4/lib/active_record/test_fixtures.rb:201:in `each'
/path/to/gems/activerecord-6.1.4/lib/active_record/test_fixtures.rb:207:in `block (2 levels) in setup_shared_connection_pool': undefined method `[]' for nil:NilClass (NoMethodError)
```

Seems like there were some recent changes to the way `setup_shared_connection_pool` works that cause `cypress-rails` to be totally unusable with this particular version of rails.

CC: @dflynn15

**Comment by gilesbowkett** [comment]
this happens because of line 71 in `manages_transactions.rb`. you can fake it out by modifying ActiveRecord's `activerecord/lib/active_record/test_fixtures.rb` like this:

![image](https://user-images.githubusercontent.com/974/124210642-08638480-daa9-11eb-9fe6-c0ee36cafa70.png)

at the risk of stating the obvious, I do not actually think you should do this in production! but it's a good way to validate my diagnosis.

the ManagesTransactions class has a method called `gather_connections`. this calls a method called `setup_shared_connection_pool`, which leads to the code in `test_fixtures.rb` in ActiveRecord exploding.

**Comment by gilesbowkett** [comment]
commenting out line 71 in `manages_transactions.rb` also works.

![line 71](https://user-images.githubusercontent.com/974/124211019-ac4d3000-daa9-11eb-9d86-0b1392a5b424.png)

**Comment by searls** [comment]
Hey Giles, sorry I hadn't had a chance to look at this previously. I'm unsure if the right option is to add a new option or just do a little more checking about either version or connection pool configuration before making this call. I'll try to look at it this week.

**Comment by gilesbowkett** [comment]
@searls all good, no rush

**Comment by searls** [comment]
Hey @gilesbowkett & @grxy -- I am somewhat confident that this particular error was just fixed in 0.5.1, but I am not confident at all that the underlying intention was ever working correctly. As a result, I'd love if you could try this out and see if you encounter any issues

**Comment by gilesbowkett** [comment]
Circle is down right now but it works fine on my machine.

I actually thought I didn't have a connection pool in the app where this came up, but after checking my `config/database.yml`, it looks like I do. so there's a bit of a 🤷🏻‍♂️ factor, but it's working.

**Comment by searls** [comment]
@gilesbowkett yeah, if you read the AR code, the only way to trigger the error you and @grxy experienced was if you _did_ have a pool in use.

Also I just switched from Circle to [GitHub Actions](https://github.com/testdouble/cypress-rails/actions) today while debugging this

**Comment by gilesbowkett** [comment]
> yeah, if you read the AR code, the only way to trigger the error you and @grxy experienced was if you did have a pool in use.

![image](https://user-images.githubusercontent.com/974/124832016-41807680-df39-11eb-91d8-cbe96a13d366.jpeg)

who reads code though

**Comment by searls** [comment]
heh, we're [on the same page](https://twitter.com/searls/status/768968698606616576?s=20)

> I learned a long time ago nobody reads code, much less verifies it. The last thing people need is more inhibition / shame.
